package token;

public enum TipoToken {
    STRING_TYPE, STRING_LITERAL,
    NUMBER_TYPE, NUMBER_LITERAL,
    LET, IDENTIFIER,
    ASSIGN, COLON, SEMI_COLON, QUOTATION,
    SPACE, TAB, NEW_LINE,
    ADICAO, SUBTRACAO, DIVISAO, MULTIPLICACAO,
    PRINT, LEFT_PAREN, RIGHT_PAREN,
    UNKOWN
}
